import Email from "./ui/email/Email";
import Footer from "./ui/footer/Footer";
import "./ui/globals.scss";
import Header from "./ui/header/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}

        {/* <div className="wrapper">
          <Header />
          <div className="main">
            {children}
          </div>
          <Email />
          <Footer />
        </div> */}
      </body>
    </html>
  );
}
